server:
  port: 9090
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  r2dbc:
    url: r2dbc:h2:mem:///fxdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password: ""
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:fxdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
app:
  jwt:
    secret: mi_clave_super_secreta_1234567890_abcdef_987654321
